### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by upsylon44** [FuckingToasters/Fake-Verification-Bot#1]
It say that :
**Task exception was never retrieved
future: <Task finished name='Task-94' coro=<RemoteAuthClient.run() done, defined at C:\Users\vicde\AppData\Roaming\Python\Python39\site-packages\remoteauthclient\remoteauthclient.py:68> exception=AssertionError()>
Traceback (most recent call last):
File "C:\Users\vicde\AppData\Roaming\Python\Python39\site-packages\remoteauthclient\remoteauthclient.py", line 106, in run
assert resp.status == 200**
![errorr](https://user-images.githubusercontent.com/114015392/191329674-0a07dbdd-f9e4-472d-addc-64f1dbf66669.PNG)

**Comment by 0deep0** [comment]
I don't know what's wrong with the bot it doesn't show the qr code anymore and gives some errors on the cmd window.

**Comment by FuckingToasters** [comment]
please let me know if the update i pushed out today solved the issue, waiting for a reply....

**Comment by FuckingToasters** [comment]
solved.
