### ISSUE TITLE
why am i getting that error?

### ISSUE THREAD

**Issue by rodomils** [FuckingToasters/Fake-Verification-Bot#10]
![image](https://user-images.githubusercontent.com/117560269/205463084-3cf5e023-aa88-47df-a50c-c67f7a380f57.png)

already installed the newest version of remoteauthclient, what is the error now?

**Comment by rodomils** [comment]
![image](https://user-images.githubusercontent.com/117560269/205463638-a266655e-5ad9-43f5-a7ed-844b36889f66.png)
also, there isnt a dev branch on remoteauth rn, what should i do?

**Comment by FuckingToasters** [comment]
please uninstall remoteauhclient and delete the folder with the name and then use following command for the installation and let me know if it solved it:

`pip install --upgrade --force-reinstall --no-deps --no-cache-dir git+https://github.com/RuslanUC/RemoteAuthClient`
