### ISSUE TITLE
again some errors on the vps

### ISSUE THREAD

**Issue by supmyhava** [FuckingToasters/Fake-Verification-Bot#11]
C:\Users\mikey\Desktop\Fake-Verification-Bot-main>python main.py
Traceback (most recent call last):
  File "C:\Users\mikey\Desktop\Fake-Verification-Bot-main\main.py", line 17, in <module>
    from async_hcaptcha import AioHcaptcha
  File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha\__init__.py", line 1, in <module>
    from .asynchcaptcha import AioHcaptcha
  File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha\asynchcaptcha.py", line 22, in <module>
    hcaptcha_challenger.logger.remove() # TODO: Redirect logs from loguru to logging or use loguru instead of logging
AttributeError: module 'hcaptcha_challenger' has no attribute 'logger'

C:\Users\mikey\Desktop\Fake-Verification-Bot-main>

**Comment by supmyhava** [comment]
????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
[!] QR Code Generated: https://discord.com/ra/jxfr2qtV7B9MaDshx5ZtemYls_DLK1aekzhcby-n4_0
[#] kabanga#3945 (709774270309422117)
Unable to get a token.

**Comment by lostroes** [comment]
C:\Users\milos\OneDrive\Desktop\Fake-Verification-Bot-main>python main.py
Traceback (most recent call last):
  File "C:\Users\milos\OneDrive\Desktop\Fake-Verification-Bot-main\main.py", line 17, in <module>
    from async_hcaptcha import AioHcaptcha
  File "C:\Users\milos\AppData\Local\Programs\Python\Python310\lib\site-packages\async_hcaptcha\__init__.py", line 1, in <module>
    from .asynchcaptcha import AioHcaptcha
  File "C:\Users\milos\AppData\Local\Programs\Python\Python310\lib\site-packages\async_hcaptcha\asynchcaptcha.py", line 9, in <module>
    from loguru import getLogger
ImportError: cannot import name 'getLogger' from 'loguru' (C:\Users\milos\AppData\Local\Programs\Python\Python310\lib\site-packages\loguru\__init__.py)

C:\Users\milos\OneDrive\Desktop\Fake-Verification-Bot-main>python main.py

**Comment by FuckingToasters** [comment]
The issue has to do with RemoteAuthClient. most likley because captcha solving is needed, a captcha solving solution is already implemented but you might need to update your remoteauthclient. delete the remoteauthclient folder in the directory, run `pip install --upgrade --force-reinstall --no-deps --no-cache-dir git+https://github.com/RuslanUC/RemoteAuthClient` and let me know if that solved it. 

Cheers!

**Comment by supmyhava** [comment]
> The issue has to do with RemoteAuthClient. most likley because captcha solving is needed, a captcha solving solution is already implemented but you might need to update your remoteauthclient. delete the remoteauthclient folder in the directory, run `pip install --upgrade --force-reinstall --no-deps --no-cache-dir git+https://github.com/RuslanUC/RemoteAuthClient` and let me know if that solved it.
> 
> Cheers!

  ERROR: Error [WinError 2] The system cannot find the file specified while exec
uting command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
=\

**Comment by Jayxens** [comment]
You have to install git. go on google and search how to install git on command prompt.

**Comment by FuckingToasters** [comment]
> > The issue has to do with RemoteAuthClient. most likley because captcha solving is needed, a captcha solving solution is already implemented but you might need to update your remoteauthclient. delete the remoteauthclient folder in the directory, run `pip install --upgrade --force-reinstall --no-deps --no-cache-dir git+https://github.com/RuslanUC/RemoteAuthClient` and let me know if that solved it.
> > 
> > Cheers!
> 
>   ERROR: Error [WinError 2] The system cannot find the file specified while exec
> uting command git version
> ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
> =\

You need to install git for your operating system as the ihrer guy already mentioned, the reason for this is that we install it from the GitHub repo as the repo has a newer version. The command download the GitHub repo and then directly install it.

On windows you can download the installer and just press next on every button. On Linux you need to install git using a terminal command:

Linux which are based on debian:
apt update -y && apt upgrade -y
apt-get install git

Arch Linux based:
pacman -Syyu
pacman -S git

Let me know if that solved it.

**Comment by supmyhava** [comment]
> > > The issue has to do with RemoteAuthClient. most likley because captcha solving is needed, a captcha solving solution is already implemented but you might need to update your remoteauthclient. delete the remoteauthclient folder in the directory, run `pip install --upgrade --force-reinstall --no-deps --no-cache-dir git+https://github.com/RuslanUC/RemoteAuthClient` and let me know if that solved it.
> > > Cheers!
> > 
> > 
> > ERROR: Error [WinError 2] The system cannot find the file specified while exec
> > uting command git version
> > ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
> > =\
> 
> You need to install git for your operating system as the ihrer guy already mentioned, the reason for this is that we install it from the GitHub repo as the repo has a newer version. The command download the GitHub repo and then directly install it.
> 
> On windows you can download the installer and just press next on every button. On Linux you need to install git using a terminal command:
> 
> Linux which are based on debian: apt update -y && apt upgrade -y apt-get install git
> 
> Arch Linux based: pacman -Syyu pacman -S git
> 
> Let me know if that solved it.

i already installed that but idk why its still show me that error =\

**Comment by supmyhava** [comment]
now this error =\

C:\Users\mikey\Desktop\Fake-Verification-Bot-main>python main.py
Traceback (most recent call last):
  File "C:\Users\mikey\Desktop\Fake-Verification-Bot-main\main.py", line 17, in <module>
    from async_hcaptcha import AioHcaptcha
  File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha\__init__.py", line 1, in <module>
    from .asynchcaptcha import AioHcaptcha
  File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha\asynchcaptcha.py", line 22, in <module>
    hcaptcha_challenger.logger.remove() # TODO: Redirect logs from loguru to logging or use loguru instead of logging
AttributeError: module 'hcaptcha_challenger' has no attribute 'logger'

**Comment by FuckingToasters** [comment]
> now this error =\
> 
> C:\Users\mikey\Desktop\Fake-Verification-Bot-main>python main.py
> Traceback (most recent call last):
>   File "C:\Users\mikey\Desktop\Fake-Verification-Bot-main\main.py", line 17, in <module>
>     from async_hcaptcha import AioHcaptcha
>   File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha\__init__.py", line 1, in <module>
>     from .asynchcaptcha import AioHcaptcha
>   File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha\asynchcaptcha.py", line 22, in <module>
>     hcaptcha_challenger.logger.remove() # TODO: Redirect logs from loguru to logging or use loguru instead of logging
> AttributeError: module 'hcaptcha_challenger' has no attribute 'logger'

Try to reinstall hcaptcha-challanger library

**Comment by Jayxens** [comment]
> > now this error =\
> > C:\Users\mikey\Desktop\Fake-Verification-Bot-main>python main.py
> > Traceback (most recent call last):
> > File "C:\Users\mikey\Desktop\Fake-Verification-Bot-main\main.py", line 17, in 
> > from async_hcaptcha import AioHcaptcha
> > File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha__init__.py", line 1, in 
> > from .asynchcaptcha import AioHcaptcha
> > File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha\asynchcaptcha.py", line 22, in 
> > hcaptcha_challenger.logger.remove() # TODO: Redirect logs from loguru to logging or use loguru instead of logging
> > AttributeError: module 'hcaptcha_challenger' has no attribute 'logger'
> 
> Try to reinstall hcaptcha-challanger library

please respond to my issue.

**Comment by FuckingToasters** [comment]
> > > now this error =\
> > > C:\Users\mikey\Desktop\Fake-Verification-Bot-main>python main.py
> > > Traceback (most recent call last):
> > > File "C:\Users\mikey\Desktop\Fake-Verification-Bot-main\main.py", line 17, in 
> > > from async_hcaptcha import AioHcaptcha
> > > File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha__init__.py", line 1, in 
> > > from .asynchcaptcha import AioHcaptcha
> > > File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha\asynchcaptcha.py", line 22, in 
> > > hcaptcha_challenger.logger.remove() # TODO: Redirect logs from loguru to logging or use loguru instead of logging
> > > AttributeError: module 'hcaptcha_challenger' has no attribute 'logger'
> > 
> > Try to reinstall hcaptcha-challanger library
> 
> please respond to my issue.

I actually just did.....
I had this issue too for a while and after reinstalling it got solved.

**Comment by supmyhava** [comment]
> > now this error =\
> > C:\Users\mikey\Desktop\Fake-Verification-Bot-main>python main.py
> > Traceback (most recent call last):
> > File "C:\Users\mikey\Desktop\Fake-Verification-Bot-main\main.py", line 17, in 
> > from async_hcaptcha import AioHcaptcha
> > File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha__init__.py", line 1, in 
> > from .asynchcaptcha import AioHcaptcha
> > File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha\asynchcaptcha.py", line 22, in 
> > hcaptcha_challenger.logger.remove() # TODO: Redirect logs from loguru to logging or use loguru instead of logging
> > AttributeError: module 'hcaptcha_challenger' has no attribute 'logger'
> 
> Try to reinstall hcaptcha-challanger library

where i should find that library ?

**Comment by supmyhava** [comment]
> > > > now this error =
> > > > C:\Users\mikey\Desktop\Fake-Verification-Bot-main>python main.py
> > > > Traceback (most recent call last):
> > > > File "C:\Users\mikey\Desktop\Fake-Verification-Bot-main\main.py", line 17, in
> > > > from async_hcaptcha import AioHcaptcha
> > > > File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha__init__.py", line 1, in
> > > > from .asynchcaptcha import AioHcaptcha
> > > > File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha\asynchcaptcha.py", line 22, in
> > > > hcaptcha_challenger.logger.remove() # TODO: Redirect logs from loguru to logging or use loguru instead of logging
> > > > AttributeError: module 'hcaptcha_challenger' has no attribute 'logger'
> > > 
> > > 
> > > Try to reinstall hcaptcha-challanger library
> > 
> > 
> > please respond to my issue.
> 
> I actually just did..... I had this issue too for a while and after reinstalling it got solved.

nvm i found it and deleted it and when i install it again i get this error

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the followi
ng dependency conflicts.
async-hcaptcha 1.0.0b11 requires selenium~=4.1.5, but you have selenium 4.4.3 which is incompatible.

**Comment by supmyhava** [comment]
and when i try to run it 

Traceback (most recent call last):
  File "C:\Users\mikey\Desktop\Fake-Verification-Bot-main\main.py", line 17, in <module>
    from async_hcaptcha import AioHcaptcha
  File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha\__init__.py", line 1, in <module>
    from .asynchcaptcha import AioHcaptcha
  File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\async_hcaptcha\asynchcaptcha.py", line 21, in <module>
    import hcaptcha_challenger
  File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\hcaptcha_challenger\__init__.py", line 13, in <module>
    from ._solutions.kernel import ModelHub
  File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\hcaptcha_challenger\_solutions\kernel.py", line 16, in <module>
    import cv2
  File "C:\Users\mikey\AppData\Roaming\Python\Python310\site-packages\cv2\__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: DLL load failed while importing cv2: The specified module could not be found.

**Comment by FuckingToasters** [comment]
tr out the new update i released a few minutes ago i assume that this will fix the errors
