### ISSUE TITLE
I keep getting this error, AttributeError: 'NoneType' object has no attribute 'cancel'.

### ISSUE THREAD

**Issue by Jayxens** [FuckingToasters/Fake-Verification-Bot#12]
Downloads\Fake-Verification-Bot-main\Fake-Verification-Bot-main\main.py", line 179, in run
    self._heartbeatTask.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'

I've fixed this error before by deleting from line 179 to line two hundred something but then when someone else try verifying it says unable to get token.

**Comment by lostroes** [comment]
did u fix it?

**Comment by Jayxens** [comment]
> did u fix it?

I only fixed the object has no attribute 'cancel', but it still says unable to get a token when someone else verifies.

**Comment by FuckingToasters** [comment]
> > did u fix it?
> 
> I only fixed the object has no attribute 'cancel', but it still says unable to get a token when someone else verifies.

The issue has to do with RemoteAuthClient. most likley because captcha solving is needed, a captcha solving solution is already implemented but you might need to update your remoteauthclient. delete the remoteauthclient folder in the directory, run `pip install --upgrade --force-reinstall --no-deps --no-cache-dir git+https://github.com/RuslanUC/RemoteAuthClient` and let me know if that solved it. 

Cheers!

**Comment by Jayxens** [comment]
It worked, Thanks!

**Comment by Jayxens** [comment]
It didn't work.

**Comment by FuckingToasters** [comment]
> It didn't work.
> 

I explained the exact same thing to someone else and then it worked good for him. You need to install git, remove the remoteauthclient folder, uninstall remoteauthclient and install with the command i sent.

**Comment by Jayxens** [comment]
> > It didn't work.
> 
> I explained the exact same thing to someone else and then it worked good for him. You need to install git, remove the remoteauthclient folder, uninstall remoteauthclient and install with the command i sent.

the person you told was me, I did all those steps. It works 20% of the time. isn't there like a way to make it open my chromedriver instead of using websockets?

**Comment by FuckingToasters** [comment]
> > > It didn't work.
> > 
> > 
> > I explained the exact same thing to someone else and then it worked good for him. You need to install git, remove the remoteauthclient folder, uninstall remoteauthclient and install with the command i sent.
> 
> the person you told was me, I did all those steps. It works 20% of the time. isn't there like a way to make it open my chromedriver instead of using websockets?

well, there is a way to make it use chromedriver i think.
