### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by mespeet** [FuckingToasters/Fake-Verification-Bot#2]
`TypeError: object of type 'NoneType' has no len()`
I am getting this error every time trying to run the main.py

`Traceback (most recent call last):
  File "D:\Fake-Verification-Bot-main\Fake-Verification-Bot-main\main.py", line 95, in <module>
    bot = commands.Bot(command_prefix=prefix, description="Fake Verification Bot - Made by Infinimonster#1312 & Astraa#6100", intents=intents)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nextcord\ext\commands\bot.py", line 1686, in __init__
    BotBase.__init__(
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nextcord\ext\commands\bot.py", line 218, in __init__
    or len(self.command_prefix) > 0`

**Comment by FuckingToasters** [comment]
> `TypeError: object of type 'NoneType' has no len()` I am getting this error every time trying to run the main.py
> 
> `Traceback (most recent call last): File "D:\Fake-Verification-Bot-main\Fake-Verification-Bot-main\main.py", line 95, in <module> bot = commands.Bot(command_prefix=prefix, description="Fake Verification Bot - Made by Infinimonster#1312 & Astraa#6100", intents=intents) File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nextcord\ext\commands\bot.py", line 1686, in __init__ BotBase.__init__( File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nextcord\ext\commands\bot.py", line 218, in __init__ or len(self.command_prefix) > 0`

Grab the new config.json. The issue was caused due to upper-lowercase text formatting in the config.json file.
