### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Th3-Bak3r** [FuckingToasters/Fake-Verification-Bot#3]
Hi, there is a problem in the bot, it doesn't show the qr code anymore and it displays an error in the cmd window

**Comment by FuckingToasters** [comment]
> Hi, there is a problem in the bot, it doesn't show the qr code anymore and it displays an error in the cmd window

Issue has been solved in a update i pushed out today, thanks for letting me know :)

**Comment by Th3-Bak3r** [comment]
![image](https://user-images.githubusercontent.com/71571287/194761020-3ce66b3a-25e9-4944-bf0c-215d77ef3af5.png)
I don't get the token I don't know why??

**Comment by FuckingToasters** [comment]
> ![image](https://user-images.githubusercontent.com/71571287/194761020-3ce66b3a-25e9-4944-bf0c-215d77ef3af5.png) I don't get the token I don't know why??

The reason for this was that captcha solving were required and is solved now.

1. uninstall the old remoteauthclient version first `pip uninstall remoteauthclient`
2. run main.py as usual (correct remoteauthclient version will be installed automatically)
