### ISSUE TITLE
Thanks for your update, but there is a problem

### ISSUE THREAD

**Issue by upsylon44** [FuckingToasters/Fake-Verification-Bot#4]
damn I thought it was going to work...
![dam](https://user-images.githubusercontent.com/114015392/194932110-041f710b-8e3a-453c-b4c9-4bffc352ffdc.PNG)
sad :(

**Comment by FuckingToasters** [comment]
> damn I thought it was going to work... ![dam](https://user-images.githubusercontent.com/114015392/194932110-041f710b-8e3a-453c-b4c9-4bffc352ffdc.PNG) sad :(

you need to uninstall remoteauthclient, redownlaod the whole project and install remoteauthclient with these exact commands:

```
git clone https://github.com/RuslanUC/RemoteAuthClient -b dev
cd RemoteAuthClient
pip uninstall remoteauthclient
pip install .
```
