### ISSUE TITLE
Maybe for Linux?

### ISSUE THREAD

**Issue by WebUwU** [FuckingToasters/Fake-Verification-Bot#5]
Cann you please make it run  on linux or Like Online host services like repilt or some shit

**Comment by FuckingToasters** [comment]
> Cann you please make it run on linux or Like Online host services like repilt or some shit

It should work on linux systems as it do on windows, what's the issue you are having?

**Comment by WebUwU** [comment]
Sorry,
The issue not on Linux just Linux based things like replit or other bot Hosting Services

**Comment by FuckingToasters** [comment]
> Sorry, The issue not on Linux just Linux based things like replit or other bot Hosting Services

you can just create a new repl and import with the github url, then use the command to start main.py (python main.py)

**Comment by WebUwU** [comment]
![Screenshot_20221113-000840_Replit](https://user-images.githubusercontent.com/44942361/201498085-ffbc45cb-435a-491d-8434-70d8c80e6820.jpg)


Get this error everytime

**Comment by WebUwU** [comment]
If you want help me better
Discord:  !Schinken#9256

**Comment by FuckingToasters** [comment]
> ![Screenshot_20221113-000840_Replit](https://user-images.githubusercontent.com/44942361/201498085-ffbc45cb-435a-491d-8434-70d8c80e6820.jpg)
> 
> Get this error everytime

reinstall hcaptcha-challanger
