### ISSUE TITLE
unable to make it works on my rdp

### ISSUE THREAD

**Issue by supmyhava** [FuckingToasters/Fake-Verification-Bot#6]
hi man
i am trying to turn on the bot from my windows vps and i get some error
![image](https://user-images.githubusercontent.com/55424004/200142556-770ecd64-cc34-4c05-91a4-b82b037f58f3.png)

**Comment by WebUwU** [comment]
pip install async_hcaptcha

I think i write it right but you see

Pip install 'Modul'

**Comment by supmyhava** [comment]
now that
![image](https://user-images.githubusercontent.com/55424004/201499143-93a440f3-fbe7-4333-837d-4c2cb10d5185.png)

**Comment by FuckingToasters** [comment]
> now that ![image](https://user-images.githubusercontent.com/55424004/201499143-93a440f3-fbe7-4333-837d-4c2cb10d5185.png)

reinstall hcaptcha-challanger
