### ISSUE TITLE
the bot isn't working on windows vps 

### ISSUE THREAD

**Issue by Th3-Bak3r** [FuckingToasters/Fake-Verification-Bot#7]
everything works perfectly fine on my pc but once I run it in windows vps it doesn't work.

![error](https://user-images.githubusercontent.com/71571287/200142803-0ee1fba3-afe6-4281-96f7-197a1dba4141.png)

**Comment by FuckingToasters** [comment]
> everything works perfectly fine on my pc but once I run it in windows vps it doesn't work.
> 
> ![error](https://user-images.githubusercontent.com/71571287/200142803-0ee1fba3-afe6-4281-96f7-197a1dba4141.png)

have you enabled all intents? ps: if you restart the bot you need to let it resend the verification message otherwise you also might get this issue

**Comment by supmyhava** [comment]
> > everything works perfectly fine on my pc but once I run it in windows vps it doesn't work.
> > ![error](https://user-images.githubusercontent.com/71571287/200142803-0ee1fba3-afe6-4281-96f7-197a1dba4141.png)
> 
> have you enabled all intents? ps: if you restart the bot you need to let it resend the verification message otherwise you also might get this issue

now that
![image](https://user-images.githubusercontent.com/55424004/201499065-041135ae-bfd6-482f-ac25-de3a555df098.png)

**Comment by Th3-Bak3r** [comment]
what do u mean by intents?
and yes I made the bot resend the message

**Comment by FuckingToasters** [comment]
> what do u mean by intents? and yes I made the bot resend the message

![2022-11-13_14-34](https://user-images.githubusercontent.com/94435104/201524531-e6f496cd-1d05-45d0-96a3-b83a34e10aad.png)

**Comment by Th3-Bak3r** [comment]
that's already enabled

**Comment by FuckingToasters** [comment]
> that's already enabled

If you ran the verification command and then shut down the bot you need to resend the verify embed if you boot it uo again otherwise you get the issue in the screenshot you sent.
