### ISSUE TITLE
hcaptcha error

### ISSUE THREAD

**Issue by rodomils** [FuckingToasters/Fake-Verification-Bot#9]
![image](https://user-images.githubusercontent.com/117560269/204951060-94d46212-c5e4-4528-8039-b29bf915c75f.png)

**Comment by FuckingToasters** [comment]
> ![image](https://user-images.githubusercontent.com/117560269/204951060-94d46212-c5e4-4528-8039-b29bf915c75f.png)

try to reinstall the hcaptcha-challanger libary.

**Comment by rodomils** [comment]
installed python 3.9 (was using 3.10 but idk if it was the problem) and reinstalled all the modules, worked now, ty <3
